### PR TITLE
Adds icon compatibility for menu bar clear mode.

### PR DESCRIPTION
**Pull request by viviangb**
In its current form, the menu bar icon doesn't support the menu bar clear mode. 

This Pull Request attempts to solve that problem by creating new icons and following the Template Image guidelines from the Electron documentation.

Addresses #7.

### CODE REVIEW

**Comment by stefanjudis** [comment]
@viviangb Thanks so much for this. It seems to work in dark and light mode now. 🎉

Was the change to "outline" icons intentional? 

Old:
screenshot 2019-01-13 09 32 12


New:
screenshot 2019-01-13 09 31 49
screenshot 2019-01-13 09 32 02

**Comment by stefanjudis** [comment]
@viviangb I see. :) I have no strong opinions here but I feel the that most of the icons in my menubar are with a fill color.

screenshot 2019-01-13 19 47 46

But if you like the outlined better we can surely role with it. :D

**Comment by viviangb** [comment]
@stefanjudis, you gave me an idea, let me try something else before you merge.

**Comment by viviangb** [comment]
@stefanjudis, I updated the icons to filled style now and you're right, they look so much better!

**Comment by viviangb** [comment]
@stefanjudis no problem, just edited the new icon and fixed the merge conflict. Let me know if you need anything else!

**Comment by stefanjudis** [comment]
This is awesome!!! 🎉 Thank you!

**Comment by stefanjudis** [comment]
Will be rolled out with `v1.2.3`. :)

**Comment by viviangb** [comment]
awesome!

**Pull request merged**
